// Generated by scripts/extract-html-projects.mjs — TAG_OVERRIDES apply on homepage cards

export type HtmlProjectMetric = { val: string; lbl: string };

export type HtmlProject = {
  id: string;
  htmlFile: string;
  tag: string;
  title: string;
  sub: string;
  eye: string;
  intro: string;
  metrics: HtmlProjectMetric[];
  featured: boolean;
  sortIndex: number;
};

export const htmlProjects: HtmlProject[] = [
  {
    "id": "infra_scheduling_project_interactive",
    "htmlFile": "infra_scheduling_project_interactive.html",
    "tag": "Flagship · Stochastic Optimization · Capital Programs",
    "title": "Robust Infrastructure Scheduling",
    "sub": "Anurag Yadav · Cornell SYSEN 5211 · Stochastic optimization for capital programs",
    "eye": "01 · Stochastic optimization · MIP · Monte Carlo",
    "intro": "Urban corridor work runs inside live traffic. This project couples a 24-task construction schedule with four daily traffic blocks, optimises cost and disruption jointly, and stress-tests the plan with 10,000 Monte Carlo runs.",
    "metrics": [
      {
        "val": "−27.3%",
        "lbl": "Traffic disruption"
      },
      {
        "val": "−$35K",
        "lbl": "Mean cost vs baseline"
      },
      {
        "val": "10,000",
        "lbl": "Monte Carlo runs"
      }
    ],
    "featured": true,
    "sortIndex": 0
  },
  {
    "id": "turbine_digital_twin_project",
    "htmlFile": "turbine_digital_twin_project.html",
    "tag": "Digital Twin · Physical Asset · Physics-Based Model",
    "title": "Wind Turbine Digital Twin",
    "sub": "Anurag Yadav · Cornell SYSEN 5490 · Browser HAWT twin with five-experiment V&V",
    "eye": "02 · Digital twin · Physics-based model · V&V",
    "intro": "A reduced-order horizontal-axis wind turbine digital twin runs in the browser. Five sequential experiments check it against analytical physics, exercise it under turbulence and transients, and document where the model must not be trusted, i",
    "metrics": [
      {
        "val": "0.48",
        "lbl": "Peak Cp (81% Betz)"
      },
      {
        "val": "19.4%",
        "lbl": "Capacity factor"
      },
      {
        "val": "7×",
        "lbl": "Surrogate AEP gap"
      }
    ],
    "featured": false,
    "sortIndex": 1
  },
  {
    "id": "mbse_bus_shelter-(1)",
    "htmlFile": "mbse_bus_shelter (1).html",
    "tag": "MBSE · SysML · Physical Infrastructure",
    "title": "Sustainable Smart Bus Shelter — CUSD / TCAT",
    "sub": "Anurag Vijay Yadav · Cornell Systems Engineering · MBSE across 32 SE tools",
    "eye": "02 · Systems Modelling · MBSE · Requirements · V&V",
    "intro": "TCAT bus stops in Ithaca are exposed infrastructure with no emergency capability, no real-time information, and grid-dependent power. This project applied 32 systems engineering tools—from stakeholder mapping through SysML, subsystem alloca",
    "metrics": [
      {
        "val": "32",
        "lbl": "SE tools applied"
      },
      {
        "val": "36",
        "lbl": "Requirements (OR+DR)"
      },
      {
        "val": "2.2kW",
        "lbl": "Solar · 72hr autonomy"
      }
    ],
    "featured": false,
    "sortIndex": 2
  },
  {
    "id": "ivv_local_gemma_llm_project",
    "htmlFile": "ivv_local_gemma_llm_project.html",
    "tag": "V&V · Stochastic AI Systems · Bounded-Behavior Verification",
    "title": "IV&V of a Locally Deployed LLM System",
    "sub": "Anurag Yadav · Cornell SYSEN 5250 · Gemma 4B · May 2026",
    "eye": "05 · Verification & validation · Statistical TC suite · Innoslate traceability",
    "intro": "Independent verification and validation of a locally deployed Gemma 4B model (Ollama) on a fixed 50-question benchmark at five decoding temperatures with five runs per cell. Every response was scored against an established evaluation rulebo",
    "metrics": [
      {
        "val": "PASS",
        "lbl": "All 5 test cases"
      },
      {
        "val": "1,250",
        "lbl": "Scored observations"
      },
      {
        "val": "93.6%",
        "lbl": "Cells CV < 0.10"
      }
    ],
    "featured": false,
    "sortIndex": 3
  },
  {
    "id": "ruga_project_v2-(3)",
    "htmlFile": "ruga_project_v2 (3).html",
    "tag": "Systems Architecture · Trade Space · DOE / MAUT",
    "title": "Next-Gen Hybrid-Electric Aircraft — RUGA",
    "sub": "Anurag Yadav · Cornell SYSEN 5400 · Tradespace architecture and feature mining · Spring 2026",
    "eye": "06 · Systems architecture · Tradespace enumeration · Feature mining",
    "intro": "A constrained tradespace study for a next-generation general aviation aircraft: enumerate feasible architectures across eight decisions (D1–D8), score cost/schedule/reliability/durability, mine dominant rules in the Pareto region, and selec",
    "metrics": [
      {
        "val": "184,212",
        "lbl": "Architectures evaluated"
      },
      {
        "val": "99.10%",
        "lbl": "Propulsion reliability"
      },
      {
        "val": "8",
        "lbl": "Architectural decisions"
      }
    ],
    "featured": false,
    "sortIndex": 4
  },
  {
    "id": "llm_simulation_project",
    "htmlFile": "llm_simulation_project.html",
    "tag": "Discrete-Event Simulation · ORIE",
    "title": "Modeling LLM Query Serving Systems",
    "sub": "Anurag Yadav · Cornell SYSEN 5580 · Discrete-event GPU scheduling simulation",
    "eye": "07 · ORIE · LLM serving · Queueing and scheduler trade studies",
    "intro": "A discrete-event simulation comparing basic FIFO assignment and chunked prefill batching for multi-GPU LLM serving under stochastic arrivals, with TTFT/TBT, queue depth, throughput, and utilization tracked across replications.",
    "metrics": [
      {
        "val": "−253 ms",
        "lbl": "P99 TTFT @ 10 GPUs"
      },
      {
        "val": "10×",
        "lbl": "Replications"
      },
      {
        "val": "80k+",
        "lbl": "Post-warmup queries"
      }
    ],
    "featured": false,
    "sortIndex": 5
  },
  {
    "id": "rag_lab_multimodal_project",
    "htmlFile": "rag_lab_multimodal_project.html",
    "tag": "Data Science · Multimodal RAG",
    "title": "RAG Lab — Lecture Assistant",
    "sub": "Anurag Yadav · Cornell SYSEN 5400 · Multimodal retrieval over course materials",
    "eye": "06 · Retrieval-augmented generation · Vision + text",
    "intro": "A local multimodal RAG stack ingests PDF and PPTX lecture decks into Chroma with per-slide or per-page chunks, optional slide preview images, and metadata for equations and diagrams. Students query via CLI or a Streamlit dashboard; answers ",
    "metrics": [
      {
        "val": "3,018",
        "lbl": "Indexed chunks"
      },
      {
        "val": "k ≤ 12",
        "lbl": "Retrieval depth"
      },
      {
        "val": "OpenAI",
        "lbl": "Primary LLM"
      }
    ],
    "featured": false,
    "sortIndex": 6
  },
  {
    "id": "news_app_project-(1)",
    "htmlFile": "news_app_project (1).html",
    "tag": "Data Science · Multi-agent AI",
    "title": "News for People in a Hurry",
    "sub": "Anurag Yadav · Cornell SYSEN 5381 · Multi-agent NYT pipeline with market validation",
    "eye": "07 · AI & data systems · Multi-agent · RAG · Tool calling",
    "intro": "A validation-first news app: ingest live NYT feeds, enrich articles with AI summaries, then run a 3-agent workflow that cross-links stories, scores world mood, and cross-references the narrative against live Yahoo Finance data before displa",
    "metrics": [
      {
        "val": "3",
        "lbl": "Agent pipeline"
      },
      {
        "val": "Live",
        "lbl": "Deployed · Posit Cloud"
      },
      {
        "val": "6",
        "lbl": "News sections + Signal Studio"
      }
    ],
    "featured": false,
    "sortIndex": 7
  }
];
